


### Listar produtos de uma loja específica (página {{Page}})
GET http://127.0.0.1:2467/api/products/byStore/Pichau/1
Content-Type: application/json

### Listar produtos de uma categoria específica (página {{Page}})
GET http://127.0.0.1:2467/api/products/category/hardware/1
Content-Type: application/json

### Listar todos os produtos (página {{Page}})
GET http://127.0.0.1:2467/api/products/all/-1
Content-Type: application/json

### Rota de Pesquisa
GET http://127.0.0.1:2467/api/products/search/Fonte/1

### Rotas de usuario #####

### Criar Usuário
POST http://127.0.0.1:2467/api/user/create HTTP/1.1
Content-Type: application/json

{
    "Email":"jonDoe@gmail.com",
    "Password":"JonDoe"
}

### Logar usuário
PATCH http://127.0.0.1:2467/api/user/login HTTP/1.1
Content-Type: application/json

{
    "Email":"jonDoe@gmail.com",
    "Password":"JonDoe"
}
#### Rotas de Issues #####

GET http://127.0.0.1:2467/api/issues/place/dev:pichau


######## Rotas Requisitos alex ############

### Listar produtos de uma categoria com filtros (Categoria: {{Category}}, Min: {{Min}}, Max: {{Max}}, Loja: {{Store}})
GET  http://127.0.0.1:2467/api/products/hardware/null--null/Pichau/1
Content-Type: application/json

### Comparar o melhor produto de todas as lojas
GET http://127.0.0.1:2467/api/products/comparasion/09922dc0-e1e0-40df-9295-7accfb50cc94
Content-Type: application/json

### Avaliação de tendências de um produto específico
GET http://127.0.0.1:2467/api/products/trends/0910beb5-489c-4428-9378-62492e58503a
Content-Type: application/json

### Retorno da lista de preços de um determinado produto
GET http://127.0.0.1:2467/api/products/prices/0910beb5-489c-4428-9378-62492e58503a
Content-Type: application/json

