#### Rotas de Issues #####

GET http://127.0.0.1:2467/api/issues/place/dev:pichau

####
GET http://127.0.0.1:2467/api/issues/1


### 
GET http://127.0.0.1:2467/api/issues/date/90


###
GET http://127.0.0.1:2467/api/scrap/date/90