### Rotas de usuario #####

### Criar Usuário
POST http://127.0.0.1:2467/api/user/create HTTP/1.1
Content-Type: application/json

{
    "Email":"xeseloc467@cctoolz.com",
    "Password":"1234"
}

### Logar usuário
PATCH http://127.0.0.1:2467/api/user/login HTTP/1.1
Content-Type: application/json

{
    "Email":"xeseloc467@cctoolz.com",
    "Password":"Flamengo"
}

### Profile 
GET http://127.0.0.1:2467/api/user/profile/e8eec215-74f7-463a-9aab-29647f3784f5

### 

GET https://hardware-price-tracker-api.onrender.com/api/user/sendcode/xeseloc467@cctoolz.com

###
PUT https://hardware-price-tracker-api.onrender.com/api/user/passbycode
Content-Type: application/json

{
        "UserProvidedCode":"728-216-355",
        "StoredCode":"728-216-355",
        "Email":"xeseloc467@cctoolz.com",
        "Password":"Flamengo"
}